runtime: nodejs
env: flex
manual_scaling:
  instances: 1
liveness_check:
  path: "/liveness_check"
readiness_check:
  path: "/readiness_check"
env_variables:
  HOST: 0.0.0.0
  GROOM_TOPIC: groom
  MAX_BATCH_SIZE: 1000
  FLUSH_INTERVAL_MS: 5000
